# Generated by Django 4.1.2 on 2023-04-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('cost', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plan_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goap.plandomain')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unspecified', max_length=10)),
                ('planDomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goap.plandomain')),
            ],
        ),
        migrations.CreateModel(
            name='ActionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('value', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goap.action')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='planDomain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goap.plandomain'),
        ),
    ]
