# Generated by Django 4.1.2 on 2023-04-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionstate',
            name='name',
        ),
    ]
