# Generated by Django 4.1.2 on 2023-04-29 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goap', '0002_remove_actionstate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionstate',
            name='variable',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='goap.variable'),
            preserve_default=False,
        ),
    ]
