# Generated by Django 4.1.2 on 2023-04-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goap', '0004_actionstate_plandomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionstate',
            name='planDomain',
        ),
    ]
