# Generated by Django 4.1.2 on 2023-04-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goap', '0005_remove_actionstate_plandomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionstate',
            name='option',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Precondition'), (2, 'Postcondition')], default=1),
        ),
    ]
