# Generated by Django 4.1.2 on 2023-04-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goap', '0006_actionstate_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goap.goal')),
                ('variable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goap.variable')),
            ],
        ),
    ]
