# Generated by Django 4.1.2 on 2023-05-06 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goap', '0007_goalstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionstate',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goap.variable'),
        ),
    ]
